name: hotkey_manager
description: This plugin allows Flutter desktop apps to defines system/inapp wide hotkey (i.e. shortcut).
version: 0.1.8
homepage: https://github.com/leanflutter/hotkey_manager

platforms:
  linux:
  macos:
  windows:

topics:
  - hotkey
  - shortcuts
  - global-hotkey
  - global-shortcuts

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  uuid: ^4.1.0

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: HotkeyManagerPlugin
      macos:
        pluginClass: HotkeyManagerPlugin
      windows:
        pluginClass: HotkeyManagerPlugin
